export const projects = [
  {
    titleEn: 'JUANA ROZAS & SIX SEX | I\'M A STAR',
    titleEs: 'JUANA ROZAS & SIX SEX | I\'M A STAR',
    title: 'JUANA ROZAS & SIX SEX | I\'M A STAR',
    href: '/shortform/juana-rozas-and-six-sex/im-a-star',
    img: '/star_web.jpeg',
  },
  {
    titleEn: 'BABASÓNICOS | ADVERTENCIA',
    titleEs: 'BABASÓNICOS | ADVERTENCIA',
    title: 'BABASÓNICOS | ADVERTENCIA',
    href: '/shortform/babasonicos/advertencia',
    img: '/adv_web.jpeg',
  },
  {
    titleEn: 'BABASÓNICOS | TAJADA',
    titleEs: 'BABASÓNICOS | TAJADA',
    title: 'BABASÓNICOS | TAJADA',
    href: '/shortform/babasonicos/tajada',
    img: '/tajada_web.jpeg',
  },
  {
    titleEn: 'ESCENA FINAL',
    titleEs: 'ESCENA FINAL',
    title: 'ESCENA FINAL',
    href: '/shortform/escena-final/trailer',
    img: '/efinal_web.jpeg',
  },
  {
    titleEn: 'NETFLIX | ABRAZA TODO LO QUE ERES',
    titleEs: 'NETFLIX | ABRAZA TODO LO QUE ERES',
    title: 'NETFLIX | NORMA',
    href: '/shortform/netflix/norma',
    img: '/netflix-norma.jpg',
  },
  {
    titleEn: 'SAMSUNG | TECH GOES GREEN | CONSCIENCE',
    titleEs: 'SAMSUNG | TECH GOES GREEN | CONSCIENCE',
    title: 'SAMSUNG | TECH GOES GREEN | A CHIP WITH CONSCIENCE',
    href: '/shortform/samsung/chip-with-conscience',
    img: '/samsung-chip.jpg',
  },
  {
    titleEn: 'SAMSUNG | TECH GOES GREEN | OUT OF THE BOX',
    titleEs: 'SAMSUNG | TECH GOES GREEN | OUT OF THE BOX',
    href: '/shortform/samsung/out-of-the-box',
    img: '/samsung-box.jpg',
  },
  {
    titleEn: 'CORONA | SUNBREW',
    titleEs: 'CORONA | SUNBREW',
    href: '/shortform/corona/sunbrew',
    img: '/corona-sunbrew.jpg',
  },
  {
    titleEn: 'BURGER KING | CONFUSING TIMES',
    titleEs: 'BURGER KING | CONFUSING TIMES',
    href: '/shortform/burger-king/confusing-times',
    img: '/bk-confusing-times.jpg',
  },
  {
    titleEn: 'SWAROVSKI | METAMORPHOSIS',
    titleEs: 'SWAROVSKI | METAMORPHOSIS',
    href: '/shortform/swarovski/metamorphosis',
    img: '/swarovsky-metamorphosis.jpg',
  },
];
